config/routes.rb
Rails.application.routes.draw do
  get '/up', to: proc { [200, {}, ['OK']] }
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "dashboard#index"
  resources :categories do
    resources :expenses, only: [ :new, :create ]
  end

  resources :expenses

  get '/dashboard', to: 'dashboard#index'

  resources :dashboard, only: [:index] do
    get 'recent_expenses', on: :collection
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  validates :name, :amount, presence: true
  has_many :expenses
  before_validation :initialize_total_amount

  def category_total
    expenses.map(&:amount).sum
    # (&:amount)shorhand for  { |expense| expense.amount }
  end

  private

  def initialize_total_amount
    self.amount ||= 0
  end

  def self.category_sum_amount(user)
    where(user_id: user.id).sum(:amount)
  end

end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :category
  after_create :update_category_total
  after_destroy :update_category_total
  belongs_to :user, optional: true
  validates :title, :amount, :date,  presence: true

  def self.total_amount_between(start_date, end_date)
    where(date: start_date..end_date).sum(:amount)
  end


  private

  def update_category_total
    category.update(amount: category.expenses.map(&:amount).sum)
  end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :expenses
  has_many :categories
  validates :email, uniqueness: true, presence:true, format: { with: Devise.email_regexp }
  after_create_commit :seed_categories
  validate :password_complexity
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    private

    def seed_categories
      ["Home", "Food", "Transport", "Going out"].each do |category|
        categories.build(name: category, amount: 0).save!
      end
    end

    def password_complexity
      if password.present?
          if !password.match(/(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.*[#?!@$%^&*-])/)
          errors.add :password, "Complexity requirement not met. Please use: 1 uppercase, 1 lowercase, 1 digit and 1 special character"
        end
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def quarter_range(quarter, date_today = Time.zone.now)
    start_date = date_today.beginning_of_year + quarter.months
    end_date = start_date.end_of_quarter
    "#{start_date.strftime('%Y-%m-%d')}|#{end_date.strftime('%Y-%m-%d')}"
  end

  def date_ranges(date_today = Time.zone.now )
    {
      "Last week" => "#{1.week.ago.beginning_of_week.strftime('%Y-%m-%d')}|#{(1.week.ago.end_of_week + 1.day).strftime('%Y-%m-%d')}",
      "This Week" => "#{date_today.beginning_of_week.strftime('%Y-%m-%d')}|#{(date_today.end_of_week + 1).strftime('%Y-%m-%d')}",
      "This month" => "#{date_today.beginning_of_month.strftime('%Y-%m-%d')}|#{date_today.end_of_month.strftime('%Y-%m-%d')}",
      "This year" => "#{date_today.beginning_of_year.strftime('%Y-%m-%d')}|#{date_today.end_of_year.strftime('%Y-%m-%d')}",
      "Q1" => quarter_range(0, date_today),
      "Q2" => quarter_range(3, date_today),
      "Q3" => quarter_range(6, date_today),
      "Q4" => quarter_range(9, date_today)
    }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @user = current_user
    @categories = @user.categories
  end

  def show

  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: "Category was successfully created."
      else
        render :new
    end
  end

    def edit
    end

    def update
      if @category.update(category_params)
        redirect_to category_path, notice: "Category was successfully updated."
      else
        render :edit
      end
    end

    def destroy
      @category.destroy
      redirect_to category_path, notice: "Category was successfully destroyed."
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:user_id, :name, :amount, :icon)
    end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :set_date_ranges
  before_action :set_filtered_expenses, only: [:index, :recent_expenses]
  def index
    @total_expenses = @expenses.sum(:amount)
  end

  def recent_expenses
    render  partial: "recent_expenses",
            locals: { expenses: @expenses },
            turbo_frame: :recent_expenses
  end

  private

  def set_date_ranges
    @date_ranges = date_ranges
  end

  def set_filtered_expenses
    @user = current_user
    @expenses = @user.expenses.order(date: :desc)
    apply_date_filters
  end

  def apply_date_filters
    if (start_date = check_and_parse_date(:start_date))
      @expenses = @expenses.where("date > ?", start_date)
    end

    if (end_date = check_and_parse_date(:end_date))
      @expenses = @expenses.where("date < ?", end_date)
    end
  end

  def check_and_parse_date(param_name)
    return nil unless params[param_name].present?
    Date.parse(params[param_name]) rescue nil
  end

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy ]
  before_action :authenticate_user!

  def index
    @user = current_user
    @expenses = @user.expenses
  end

  def show
  end

  def new
    @expense = Expense.new
  end

  def create
    @expense = Expense.new(expense_params)
    if @expense.save
      redirect_to expenses_path, notice: "Expense was successfully created."
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @expense.update(expense_params)
      redirect_to expenses_path, notice: "Expense was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @expense.destroy
    redirect_to expenses_path, notice: "Expense was successfully deleted."
  end

  private

  def set_expense
    @expense = Expense.find(params[:id])
  end


  def expense_params
    params[:expense].permit(:title, :amount, :date, :category_id, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/categories/_form.html.erb
<div class="container">
  <h1>New Category</h1>

  <%= simple_form_for @category do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id  %>

  <%= f.input :name %>
  <%= f.hidden_field :amount, value: 0  %>
  <%# <%= f.input :amount %>

  <%= f.submit "Submit now", class: "btn btn-primary" %>
  <%= link_to 'Back to Categories', categories_path, class: 'btn btn-primary mt-4 back' %>
<% end %>

</div>

app/views/categories/edit.html.erb
<%= render "form" %>

app/views/categories/index.html.erb
<h1>Welcome to Spend wise</h1>

<div class= "list">
  <ul data-controller="position">
    <% @categories.each do |category| %>
      <li class="category-item">
        <span class="category-name"><%= category.name %></span>
        <span class="category-amount"><%= category.category_total %></span>
         <span class="category-amount"><%= link_to 'Edit', edit_category_path(category) %></span>
          <span class="category-amount "><%= button_to 'Delete', category_path(category), method: :delete, data: { confirm: 'Are you sure?' },  class: 'btn' %></span>
      </li>
    <% end %>
  </ul>
</div>

<div>
  <h1>Total Spent: £<%= Category.category_sum_amount(current_user) %></h1>
</div>

<%= link_to 'New Category', new_category_path  %>
<%# <%= image_tag "icon.png", alt: "Categories Icon" %>

<%# <a href="https://www.freepik.com/icon/balanced-diet_6774898#fromView=search&page=1&position=73&uuid=a8be3c28-d9f4-4694-bdb1-2876523dd9f2">Icon by paulalee</a> %>

app/views/categories/new.html.erb
<%= render "form" %>

app/views/dashboard/_recent_expenses.html.erb
<%= turbo_frame_tag :recent_expenses do %>
  <ul>
    <% @expenses.each do |expense| %>
      <li>
        <%= expense.category.name %> - <%= expense.title %>- £<%= expense.amount %> on <%= expense.date.strftime("%B %d, %Y") %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/dashboard/index.html.erb
<div class="container"data-controller="date-filter">

  <h1>Welcome, <%= @user.username %>!</h1>

  <br>

  <div class="date-label-container d-flex align-items-center">
    <p class="start-day mr-1"> Start date </p>
    <%# <p class="end-day ml-1"> End date </p> %>
  </div>

  <%= turbo_frame_tag "date_filter_form" do %>
    <%= form_tag dashboard_path, method: :get, class: "d-flex", data:{turbo_frame:"expenses", turbo_action: "advance"} do %>
      <div>
        <div class="date-input-wrapper-start">
          <input type="date"
                id="start_date"
                name="start_date"
                class="form-control"
                value="<%= params[:start_date] || '' %>"
                placeholder="Start Date"
                data-date-filter-target="startDate">
        </div>
        <div class="date-input-wrapper-end">
          <input type="date"
                id="end_date"
                name="end_date"
                class="form-control"
                value="<%= params[:end_date] || '' %>"
                placeholder="End Date"
                data-date-filter-target="endDate">
        </div>
          <%= submit_tag "Search", class: "btn btn-primary" %>

      </div>

        <br>

      <div>
        <label for="date-filter">Filter by date:</label>
        <select id="date-filter" name="date_filter"  data-date-filter-target="dateFilter" data-action="change->date-filter#updateDateFilter">
          <option value=""> </option>
          <% @date_ranges.each do |k,v| %>
          <option
            value="<%= k %>"
            data-filter="<%= v %>"
            <%= params[:date_filter] == k ? "selected" : "" %>>
            <%= k %>
          </option >
          <% end %>
        </select>
      </div>
    <% end %>
  <% end %>

  <br>

  <%= turbo_frame_tag "expenses" do %>
    <div class="container">
      <div class="row mt-5">
        <div class="col-md-4">
          <div class="card bg-light mb-3" style="width: 15rem;height: 120px;">
            <div class="card-body">
              <p class="card-text text-center">Total Expenses</p>
              <p class="card-text text-center">£<%= number_with_precision(@total_expenses, precision: 2) %></p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container" >
      <h2>Your Recent Expenses</h2>
      <%= render partial: "recent_expenses" %>
    </div>

  <% end %>
</div>

app/views/expenses/_form.html.erb
<div class="container">
  <h1>New Transaction</h1>

  <%= simple_form_for @expense, remote: true, html: { data: { action: "ajax:success->date-filter#refreshTotalExpenses" } }  do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id  %>
  <%= f.input :title %>
  <%= f.input :amount %>
  <%= f.input :date %>
  <%= f.association :category,
                    collection: current_user.categories,
                    label_method: :name,
                    value_method: :id,
                    include_blank: false %>
  <%# <%= f.association :category, label_method: :name, value_method: :id, include_blank: false %>

  <%= f.submit "Submit now", class: "btn btn-primary" %>
  <%= link_to 'Back to Expenses', expenses_path, class: 'btn btn-primary mt-4 back' %>
<% end %>

</div>

app/views/expenses/index.html.erb
<h1>Hi <%= current_user.username %>!</h1>

<div>
  <ul class="horizontal-list">

      <li class="table_title table_transaction"> Transaction</li>
      <li class="table_title table_amount"> Amount</li>
      <li class="table_title table_date"> Date</li>
      <li class="table_title"> Category</li>
  </ul>
</div>

<div class= "list">
    <ul data-controller="position">
      <% @expenses.each do |expense| %>
        <li class="category-item">
          <span class="category-name"><%= expense.title %></span>
          <span class="category-amount">£<%= expense.amount %></span>
          <span class="category-amount"><%= expense.date.strftime("%d/%m/%y - %R") %></span>
          <span class="category-amount"><%= expense.category.name %></span>
          <span class="category-amount"><%= link_to 'Edit', edit_expense_path(expense) %></span>
          <span class="category-amount "><%= button_to 'Delete', expense_path(expense), method: :delete, data: { confirm: 'Are you sure?' },  class: 'btn' %></span>

        </li>
      <% end %>
    </ul>
  </div>

  <%= link_to 'New Expense', new_expense_path  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spendwise</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%# <p class="notice"><%= notice %>
    <%# <p class="alert"><%= alert %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-secondary alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark p-3 navbar-div" style="background-color: #8d81ff;">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "",style: "height: 40px; width: auto;" %>
    <% end %>
    <%# <a class="navbar-brand" href="#">Navbar</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class=" collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ms-auto ">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link mx-2 active", aria: { current: "page" } %>
        </li>
        <li class="nav-item">
          <%= link_to "Expenses", expenses_path, class: "nav-link mx-2 active" %>
          <%# <a class="nav-link mx-2" href="#">Patients</a> %>
        </li>
        <li class="nav-item">
          <%= link_to "Categories", categories_path, class: "nav-link mx-2 active" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link mx-2 active dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Login
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a><%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item colour-text" %></a></li>
            <li><a class="dropdown-item" href="#">About Us</a></li>
            <li><a class="dropdown-item" href="#">Contact us</a></li>
          </ul>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>